stages:
  - build
  - build-docker

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - node_modules/

# Master
build-master-php:
  stage: build
  image: php:7.2
  only:
    - master
    - tags
  before_script:
    - set -xe
    - apt-get update -yqq
    - apt-get install git wget zip unzip -yqq
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - docker-php-ext-install pdo_mysql
  script:
    - cp .env.example .env
    - php composer.phar install --ignore-platform-reqs --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
    - php artisan key:generate
    - vendor/bin/phpunit
  artifacts:
    paths:
      - ./vendor

build-master-frontend:
  stage: build
  image: node:8.11
  only:
    - master
    - tags
  script:
    - yarn install
    - yarn run production
  artifacts:
    paths:
      - ./public/js
      - ./public/css
      - ./public/mix-manifest.json

build-master-docker:
  stage: build-docker
  image: docker:stable
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE"

build-tag-docker:
  stage: build-docker
  image: docker:stable
  only:
    - tags
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" -f docker/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
